version: '3.5'
services:
  #------------------#
  # Producer Service #
  #------------------#
  product-service:
    # Note: horizontal scalability clashes with container names
    #container_name: product-service.local
    image: product-service:local
    ports:
      - 51080-51081:8080
      - 51800-51801:8000
    depends_on:
      - product-service-database
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.http.routers.product-service.rule=PathPrefix(`/products`)
      - traefik.http.services.product-service.loadbalancer.server.port=8080
  #-----------------------#
  # Shopping Cart Service #
  #-----------------------#
  shopping-cart-service:
    container_name: shopping-cart-service.local
    image: shopping-cart-service:local
    ports:
      - 52080:8080
      - 52800:8000
    depends_on:
      - shopping-cart-service-database
      - kafka
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.http.routers.shopping-cart-service.rule=PathPrefix(`/cart`)
      - traefik.http.services.shopping-cart-service.loadbalancer.server.port=8080
  #---------------#
  # Order Service #
  #---------------#
  order-service:
    container_name: order-service.local
    image: order-service:local
    ports:
      - 53080:8080
      - 53800:8000
    depends_on:
      - order-service-database
      - kafka
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.http.routers.order-service.rule=PathPrefix(`/orders`)
      - traefik.http.services.order-service.loadbalancer.server.port=8080
  #-----------------#
  # Payment Service #
  #-----------------#
  payment-service:
    container_name: payment-service.local
    image: payment-service:local
    ports:
      - 54080:8080
      - 54800:8000
    depends_on:
      - kafka
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.http.routers.payment-service.rule=Host(`localhost`)
      - traefik.http.services.payment-service.loadbalancer.server.port=8080
  #-----------------#
  # Account Service #
  #-----------------#
  account-service:
    container_name: account-service.local
    image: account-service:local
    ports:
      - 55080:8080
      - 55800:8000
    depends_on:
      - kafka
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.http.routers.account-service.rule=PathPrefix(`/graphql`)
      - traefik.http.services.account-service.loadbalancer.server.port=8080
  #------------------#
  # Shipping Service #
  #------------------#
  shipping-service:
    container_name: shipping-service.local
    image: shipping-service:local
    ports:
      - 56080:8080
      - 56800:8000
    depends_on:
      - kafka
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.http.routers.shipping-service.rule=Host(`localhost`)
      - traefik.http.services.shipping-service.loadbalancer.server.port=8080
  #------------------#
  # Notification Service #
  #------------------#
  notification-service:
    container_name: notification-service.local
    image: notification-service:local
    ports:
      - 57080:8080
      - 57800:8000
    depends_on:
      - kafka
    networks:
      - ecommerce-network
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
      - SPRING_PROFILES_ACTIVE=dockerlocal
    labels:
      - traefik.enable=true
      - traefik.http.routers.notification-service.rule=Host(`localhost`)
      - traefik.http.services.notification-service.loadbalancer.server.port=8080
networks:
  ecommerce-network:
    name: ecommerce-app