version: '3.5'
services:
  #------------------#
  # Debezium Connect #
  #------------------#
  # Note: starting version 2.0, Confluent Avro converters were removed from the Docker image
  # You have to build your own image and add the missing jar files
  # https://stackoverflow.com/questions/74763985/debezium-docker-compose-mysql-avro-worker-yaml-connector-issue-class-io-conflue
  debezium-connect:
    container_name: debezium-connect.local
    image: debezium/connect:1.9.6.Final
    networks:
      - ecommerce-network
    depends_on:
      - kafka
    ports:
      - 18083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:19092
      REST_PORT: 8083
      GROUP_ID: ecommerce-debezium-connect-group-id
      CONFIG_STORAGE_TOPIC: ecommerce-debezium-connect-configs
      OFFSET_STORAGE_TOPIC: ecommerce-debezium-connect-offsets
      STATUS_STORAGE_TOPIC: ecommerce-debezium-connect-status
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry.local:18081
      VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry.local:18081
  #-------------#
  # Debezium UI #
  #-------------#
  debezium-ui:
    container_name: debezium-ui.local
    image: debezium/debezium-ui:2.2
    networks:
      - ecommerce-network
    depends_on:
      - debezium-connect
    ports:
      - 18080:8080
    environment:
      KAFKA_CONNECT_URIS: http://debezium-connect.local:8083
networks:
  ecommerce-network:
    name: ecommerce-app