---
openapi: 3.0.3
info:
  title: eCommerce Products Api
  version: "1.0"
paths:
  /products:
    get:
      tags:
        - "Product"
      summary: Return all products
      parameters:
        - in: query
          name: productIds
          description: Product Ids
          schema:
            type: array
            items:
              type: string
              description: Product unique id
              format: uuid
          required: false
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
        "500":
          description: Internal server error
    post:
      tags:
        - "Product"
      summary: Create a new product
      requestBody:
        description: Product content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateDto'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductIdDto'
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /products/{productId}:
    get:
      tags:
        - "Product"
      summary: Return product by id
      parameters:
        - in: path
          name: productId
          description: Product Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        "404":
          description: Not found
        "500":
          description: Internal server error
    patch:
      tags:
        - "Product"
      summary: Partial update a product by id
      parameters:
        - in: path
          name: productId
          description: Product Id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: Partial update content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdateDto'
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error
    delete:
      tags:
        - "Product"
      summary: Delete a product by id. Not yet implemented
      parameters:
        - in: path
          name: productId
          description: Product Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
        "404":
          description: Not found
        "500":
          description: Internal server error
        "501":
          description: Not implemented
components:
  schemas:
    ProductDto:
      type: object
      properties:
        productId:
          type: string
          description: Product unique id
          format: uuid
      allOf:
        - $ref: '#/components/schemas/ProductCreateDto'
        - $ref: '#/components/schemas/ProductIdDto'
    ProductCreateDto:
      type: object
      properties:
        name:
          type: string
          description: Product name
          maxLength: 512
          example: "Barista Espresso Italiano"
        brand:
          type: string
          description: Brand
          maxLength: 256
          example: "Jacobs"
        category:
          type: string
          description: Category
          maxLength: 256
          example: "Coffee"
        price:
          type: number
          format: double
          description: Product price
          example: 15
        currency:
          type: string
          description: Product currency
          enum: [EUR]
          example: EUR
        quantity:
          type: integer
          description: Product quantity
          example: 100
    ProductUpdateDto:
      type: object
      properties:
        quantity:
          type: integer
          description: Product quantity
          example: 2
        price:
          type: number
          format: double
          description: Product price
          example: 3
    ProductIdDto:
      type: object
      properties:
        productId:
          type: string
          description: Product unique id
          format: uuid