---
openapi: 3.0.3
info:
  title: eCommerce Shopping Cart Api
  version: "1.0"
paths:
  /cart/{userId}/items:
    post:
      tags:
        - "Cart Item"
      summary: Add shopping items to the user's cart
      parameters:
        - in: path
          name: userId
          description: User Id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: Cart content
        required: true
        content:
          application/json:
            schema:
              type: array
              maxItems: 16
              items:
                $ref: '#/components/schemas/CartItemCreateDto'
      responses:
        "201":
          description: Created
        "400":
          description: Bad request
        "403":
          description: Forbidden
        "500":
          description: Internal server error
    get:
      tags:
        - "Cart Item"
      summary: Return all shopping items from the user's cart
      parameters:
        - in: path
          name: userId
          description: User Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItemDto'
        "500":
          description: Internal server error
    delete:
      tags:
        - "Cart Item"
      summary: Delete all shopping items from the user's cart
      parameters:
        - in: path
          name: userId
          description: User Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
        "404":
          description: Not found
        "500":
          description: Internal server error
  /cart/{userId}/items/{itemId}:
    get:
      tags:
        - "Cart Item"
      summary: Return a shopping item from the user's cart by item id. Not yet implemented
      parameters:
        - in: path
          name: userId
          description: User Id
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: itemId
          description: Item Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItemCreateDto'
        "404":
          description: Not found
        "500":
          description: Internal server error
        "501":
          description: Not implemented
    put:
      tags:
        - "Cart Item"
      summary: Update a shopping item from the user's cart item id. Not yet implemented
      parameters:
        - in: path
          name: userId
          description: User Id
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: itemId
          description: Item Id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: Partial update content
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItemUpdateDto'
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error
        "501":
          description: Not implemented
    delete:
      tags:
        - "Cart Item"
      summary: Delete a shopping item from the user's cart item id. Not yet implemented
      parameters:
        - in: path
          name: userId
          description: User Id
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: itemId
          description: Item Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: Success
        "404":
          description: Not found
        "500":
          description: Internal server error
        "501":
          description: Not implemented
  /cart/{userId}/checkout:
    post:
      tags:
        - "Cart Item"
      summary: Checkout the shopping cart and create an order event
      parameters:
        - in: path
          name: userId
          description: User Id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "202":
          description: Accepted
        "404":
          description: Not found
        "403":
          description: Forbidden
        "500":
          description: Internal server error
components:
  schemas:
    CartItemDto:
      type: object
      allOf:
        - $ref: '#/components/schemas/CartItemIdDto'
        - $ref: '#/components/schemas/CartItemCreateDto'
    CartItemCreateDto:
      type: object
      properties:
        productId:
          type: string
          description: Product unique id
          format: uuid
        quantity:
          type: integer
          description: Product quantity
          example: 3
        discount:
          type: number
          format: double
          description: Discount on percentage rate
          example: 1.1
    CartItemUpdateDto:
      type: object
      properties:
        quantity:
          type: integer
          description: Cart quantity
          example: 2
    CartItemIdDto:
      type: object
      properties:
        itemId:
          type: string
          description: Cart item unique id
          format: uuid